[tool.poetry]
name = "whyqa"
version = "0.1.0"
description = ""
authors = ["Italo Silva <italo@maleldil.com>"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
openai = ">=1.0,<2.0"
pandas = ">=1.0,<2.0"
readchar = ">=4.0,<5.0"
scikit-learn = ">=1.0,<2.0"
tqdm = ">=4.0,<5.0"
typer = ">=0.9,<1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
